### ISSUE TITLE
Shell error: Can't shift that many

### ISSUE THREAD

**Issue by alehaa** [nemequ/pgi-travis#1]
When using the script with `/bin/sh` and arguments (`--mpi`), I get the following error:

```
/dev/stdin: 64: shift: can't shift that many
```

**Comment by nemequ** [comment]
I pushed a commit (4913436ec404348866d9abf3694dbec775addfe3) to the staging branch, can you confirm that it fixes the issue?

If not, what provides /bin/sh on your system (bash, dash, zsh, etc.)?

**Comment by nemequ** [comment]
Reproduced with dash, and this does seem to fix it, so I'm going to push to master and mark this as closed.  Please reopen this if it doesn't work for you.

**Comment by alehaa** [comment]
Dash is right, as this is the default shell for Debian / Ubuntu and so for Travis CI. Works now, thanks! ;)
