### ISSUE TITLE
PGI download moved?

### ISSUE THREAD

**Issue by codylico** [nemequ/pgi-travis#3]
NVIDIA may have changed URIs for the SDK download landing page. As a (possible) result, the install script breaks, causing the Travis CI test to fail.

The possible fix may be simply to update the link in the `install_pgi.sh` script, but I haven't tested that theory. Let me know if you get a chance to look at it, and if you prefer that I attempt to repair the script myself.

#### Links:
- The failing CI test: [https://travis-ci.com/github/codylico/munit-plus/jobs/399173823](https://travis-ci.com/github/codylico/munit-plus/jobs/399173823)
- The new downloads location on NVIDIA: [https://developer.nvidia.com/nvidia-hpc-sdk-downloads](https://developer.nvidia.com/nvidia-hpc-sdk-downloads)

**Comment by nemequ** [comment]
They… added an s at the end.  It's now https://developer.nvidia.com/nvidia-hpc-sdk-downloads instead of https://developer.nvidia.com/nvidia-hpc-sdk-download.

They also moved the downloads into a different folder, which seems more reasonable.

I pushed some changes, it should work now.

**Comment by codylico** [comment]
It works! Thank you.
